### PR TITLE
Sprite Directory Restructure 

### PR DESCRIPTION
**Pull request by quigley-c**
## What changed?
The sprite dir is getting cluttered. This PR aims to restructure the sprite dirs for more a more organized approach.

### CODE REVIEW

**Comment by quigley-c** [comment]
@codeandkey can you modify the sprite loading sequence to allow for this? I am unfamiliar with the code here.

**Comment by codeandkey** [comment]
Right now the sprite loader only considers the basename of the sprite name passed to it; so any directory structure will be tossed out. This is because of how Tiled tilesets store the path to the tileset images. To get around this we can define multiple functions for loading sprites, or perhaps a flag in the loader to not `basename` the path.

**Comment by codeandkey** [comment]
With the new commit here this should be implemented. It looks like the map will need to be updated to use the new sprite paths.

**Comment by quigley-c** [comment]
@codeandkey none of the sprites seem to be loading properly anymore

**Comment by quigley-c** [comment]
never mind, fixed.

**Pull request merged**
