### PR TITLE
Adds Controls menu under options

### PR DESCRIPTION
**Pull request by ZachAndrews98**
This code is not necessarily the best written, but it does work, so if there are any spots that I should change let me know. In order to get out of the controls menu, you have to hit the down arrow which will then select "OK" and hit enter. This will bring you back to the main menu, not the options menu, as of right now.

### CODE REVIEW

**Comment by codeandkey** [comment]
I like this idea a lot -- however on my display the other options are pushed below the screen and only partially visible. I think that in the long run the main menu may need a complete rewrite and should probably be split into several different objects for selectors, options, etc.

Something that also might be useful in several parts of the game would be to have an input-independent way to display a "key" on the screen. I think _Crypt of the Necrodancer_ did this particularly well. The controls are displayed alongside the action making it very easy to figure out how to play.
necrodancer

**Comment by quigley-c** [comment]
@codeandkey That's quite an idea, and I think it's not totally unfeasible. There is a lot of work that needs to be done for the game's HUD currently, as we haven't made and intentional decisions on that front yet. If we want to display keybinds on-screen we need to be aware of the visual clutter our HUD might create, though that can be discussed in more detail when we get it working. 

It might be possible to have the game be able to resize text based on current display resolution to fit the enements on-screen, though it might be more practical just to allow the camera to scroll with the input selector object. If that seems like too much work right now, we can also just split the menu up one more time, which as @codeandkey mentioned already, it likely necessary anyway. I'm thinking we can simply split it up into two categories under `options`: `video` and `controls`. We can add others to this sub-menu as we implement more features like sound, compatibility settings, etc.

**Comment by quigley-c** [comment]
@codeandkey what should we do about this? Is a menu rewrite on the horizon?

**Comment by codeandkey** [comment]
@quigley-c I think it is definitely time to open a PR for a new HUD subsystem; this might be better addressed afterwards.

**Pull request merged**
