### PR TITLE
Readme update - post ecs refactor

### PR DESCRIPTION
**Pull request by quigley-c**
## What changed?
The readme has become outdated since the ecs-refactor has been merged. It needs to be updated with the new features and possibly rewritten in some sections. This PR has an initial commit as an example, though plenty more updates are needed.

### CODE REVIEW

**Comment by quigley-c** [comment]
@codeandkey can you update the readme with some of the changes from the refactor?

**Comment by codeandkey** [comment]
This is ready for review. With the introduction of HTML docs I think we can move much of the developer documentation there in the future.

**Comment by quigley-c** [comment]
The README.md should include instructions for opening and reading the HTML docs then.

**Comment by quigley-c** [comment]
Merging.

**Pull request merged**
