### PR TITLE
Multiple input mapping

### LINKED ISSUE #80: Multiple input mapping
The input system needs to be rewritten. Currently input events are generated from `main.lua`, but the system should be written so the events are generated from the `input` subsystem.

A key can only bind to one game input, but the mapping should be inverted -- game inputs should be mapped to keys and then looked up from a constant table.

### PR DESCRIPTION
**Pull request by codeandkey**
This PR changes the input subsystem to allow binding one key to several inputs, or multiple keys to one input. It replaces the 'translate' input method with a more functional one.

Closes #80

### CODE REVIEW

**Comment by quigley-c** [comment]
Would it be worth it to have a `keybind` section in `options` for this or would it be better to have a separate PR for it?

**Comment by codeandkey** [comment]
Having a menu for keybinds could be complicated to add -- maybe this should be backlogged as a future feature?

**Comment by quigley-c** [comment]
With the addition of the input menu in #107 we should revisit this @codeandkey

**Comment by quigley-c** [comment]
@codeandkey is this still relevant / useful?

**Comment by quigley-c** [comment]
old, please create a new PR for the refactored menu if you intend to pursue this idea.

**Pull request closed without merging**
